> 本文由 [简悦 SimpRead](http://ksria.com/simpread/) 转码， 原文地址 [bbs.pediy.com](https://bbs.pediy.com/thread-270045.htm)

> [原创] 内核学习 - 异常处理

内核学习 - 异常
=========

异常产生后，首先是要**记录异常信息**（异常的类型、异常发生的位置等），然后要寻找异常的处理函数，称为**异常的分发**, 最后找到异常处理函数并调用，称为**异常处理**。

 

围绕 `异常处理`，`异常分发`，`异常处理`展开

 

**异常的分类：**

 

（1）cpu 产生的异常

 

[外链图片转存失败, 源站可能有防盗链机制, 建议将图片保存下来直接上传 (img-ZYiH89U2-1635589257293)(C:\Users\lenovo\AppData\Roaming\Typora\typora-user-images\image-20211008111448624.png)]

 

代码执行时，CPU 检测到除数为零, cpu 抛出异常

 

（2）软件模拟产生的异常

 

在 C++ 或者是 C# 等一些高级语言中，在程序需要的时候也可以主动抛出异常，这种高级语言抛出的异常就是模拟产生的异常，并不是真正的异常。

 

![](https://img-blog.csdnimg.cn/img_convert/4f270d079a4898ad7db88bef2d262c1a.png)

 

**异常记录**

1.CPU 异常记录
----------

### 1.CPU 异常的处理流程

> 1.  CPU 指令检测到异常（例：除零）
> 2.  查 IDT 表 (如下表)，执行中断处理函数
> 3.  CommonDispatchException
> 4.  KiDispatchException

 

![](https://img-blog.csdnimg.cn/20200320143749200.png?)

 

![](https://img-blog.csdnimg.cn/img_convert/1d42976370c5953487b12d1927decf55.png)

 

找中断表的 0 号处理函数，

 

截图百度百科：

 

[外链图片转存失败, 源站可能有防盗链机制, 建议将图片保存下来直接上传 (img-YtGLZUvB-1635589257299)(C:\Users\lenovo\AppData\Roaming\Typora\typora-user-images\image-20211008133552281.png)]

 

IDA 打开 **ntoskrnl.exe** 搜索字符串 **_IDT** 进行定位

 

IDT 表：

 

[外链图片转存失败, 源站可能有防盗链机制, 建议将图片保存下来直接上传 (img-pq9lEUC1-1635589257301)(C:\Users\lenovo\AppData\Roaming\Typora\typora-user-images\image-20211008114554726.png)]

### 2. 分析中断处理函数 _KiTrap00

**执行流程**：

1.  **保存现场** (将寄存器堆栈位置等信息保存到 **_Trap_Frame** 中)
2.  调用 **CommonDispatchException** 函数

[外链图片转存失败, 源站可能有防盗链机制, 建议将图片保存下来直接上传 (img-9cmiIq8l-1635589257302)(C:\Users\lenovo\AppData\Roaming\Typora\typora-user-images\image-20211008114945625.png)]

 

![](https://img-blog.csdnimg.cn/img_convert/d2f660baacdf48b8ffe713cbdd0b46e0.png)

 

4018c7 函数：没有对异常进行处理，函数内部调用 **CommonDispatchException** 函数

 

![](https://img-blog.csdnimg.cn/img_convert/5db3c99b9ca4e38e46d85067978d88e3.png)

 

**CommonDispatchException** 函数内部调用**_KiDispatchExceptio**，CPU 这么设计的目的是为了让程序员有机会对异常进行处理。

 

![](https://img-blog.csdnimg.cn/img_convert/d2d7d50c6842178ab954116395f9281f.png)

 

**总结**：

1.  异常处理函数中并没有直接对异常进行处理，而是调用了 **CommonDispatchException**
2.  这样设计异常的**目的**是为了程序员有机会对异常进行处理

### 3.CommonDispatchException 函数分析

该函数构造一个`_EXCEPTION_RECORD`结构体 并赋值

 

[外链图片转存失败, 源站可能有防盗链机制, 建议将图片保存下来直接上传 (img-ZadewdoA-1635589257306)(C:\Users\lenovo\AppData\Roaming\Typora\typora-user-images\image-20211008134756847.png)]

 

CommonDispatchException 主要就做了一件事情，就是将异常相关的信息存储到一个`_EXCEPTION_RECORD`结构体里，这个结构体的作用就是用来记录异常信息

```
type struct _EXCEPTION_RECORD       
{                               
    DWORD ExceptionCode;                //异常代码
    DWORD ExceptionFlags;                //异常状态
    struct _EXCEPTION_RECORD* ExceptionRecord;    //下一个异常
    PVOID ExceptionAddress;                //异常发生地址
    DWORD NumberParameters;            //附加参数个数
    ULONG_PTR ExceptionInformation
    [EXCEPTION_MAXIMUM_PARAMETERS];        //附加参数指针   
}

```

![](https://img-blog.csdnimg.cn/img_convert/e41bed49f26e388e8af54cece0fc019d.png)

 

ebx 中存储的是发生异常时的 EIP，eax：0C0000094h ，这个是 CPU 自己在内部定义的异常代码

 

**ExceptionFlags 异常状态**：通过异常状态可以区分是 CPU 产生的异常还是软件模拟产生的异常。所有的 CPU 产生的异常这个位置的值是 0，所有软件模拟产生的异常这个位置存储的值是 1，如果堆栈错误里面存储的值是 8，如果出现嵌套异常，里面存储的值是 0x10

 

**ExceptionRecord 下一个异常**：通常是空的，但是出现嵌套异常，通过指针指向下一个异常。

### 4. 总结

CPU 异常的执行流程：

1.  CPU 指令检测到异常
2.  查 IDT 表，执行中断处理函数
3.  调用 CommonDispatchException（构建`EXCEPTION_RECORD结构体`）
4.  KiDispatchException（`分发异常`：目的是为了找到异常处理函数）

2. 模拟异常记录
---------

示例代码：通过代码抛出异常 **throw 关键字**

 

[外链图片转存失败, 源站可能有防盗链机制, 建议将图片保存下来直接上传 (img-RnofQv8u-1635589257308)(C:\Users\lenovo\AppData\Roaming\Typora\typora-user-images\image-20211008140102784.png)]

 

当通过软件抛出异常的时候，实际上就是调用了`CxxThrowException`

 

![](https://img-blog.csdnimg.cn/img_convert/78ab4804b6091daf42f01f7058473c5a.png)

 

`CxxThrowException`调用（KERNEL32.DLL）RaiseException

### RaiseException 分析

在堆栈里构建一个`EXCEPTION_RECORD`结构体，然后对结构体进行赋值

 

![](https://img-blog.csdnimg.cn/img_convert/2c1c5c7c2b70584f3a23c9bf39f81f34.png)

 

CPU 产生的异常和软件模拟产生的异常都填充`EXCEPTION_RECORD`结构体，但是两者有差异

 

差异：

 

**ExceptionCode 异常代码**

 

当 CPU 产生异常时会记录一个 **ErrorCode**，通过查表可以查到 ErrorCode 具体的含义，不同的异常对应不同的错误代码，但是软件抛出的 ErrorCode 是根据编译环境决定的，如下图的 EDX 中存储的值即为当前编译环境的 ErrorCode

 

![](https://img-blog.csdnimg.cn/img_convert/408d672199979f56332114a72c6a8c94.png)

 

**ExceptionAddress 异常发生地址**

 

第二个区别就是 ExceptionAddress，CPU 异常记录的位置是真正的异常发生时的地址

 

![](https://img-blog.csdnimg.cn/img_convert/5bc43137891a876cbec778e3b107e006.png)

 

**CPU** 记录异常的地址是真正发生异常的地址, 软件模拟产生的异常里面存储的是`RaiseException`这个函数的地址。

### RaiseException 函数分析

**RaiseException** 调用 **RtlRaiseException** （ntdll.dll）

 

![](https://img-blog.csdnimg.cn/img_convert/1a249e36969a42822ac340f78b356bdb.png)

 

**RtlRaiseException** 调用**_ZwRaiseException**

 

![](https://img-blog.csdnimg.cn/img_convert/f5768c84634e3df2dbec2f80fe158115.png)

 

**_ZwRaiseException** 调用 **NtRaiseException**

 

![](https://img-blog.csdnimg.cn/img_convert/7b188078811e80f240ac211f64302db1.png)

 

**NtRaiseException** 调用**_KiRaiseException**

 

这个函数主要做了两件事

> 1.  把 EXCEPTION_RECORD 结构体的 ExceptionCode 最高位清零，用于区分 CPU 异常
> 2.  调用 KiDispatchException 开始分发异常

 

![](https://img-blog.csdnimg.cn/img_convert/9cc29c4b0a9e42a2b744edb01a3c0339.png)

 

![](https://img-blog.csdnimg.cn/20200216181255268.png?)

 

RaiseException 在初始化一个 EXCEPTION_RECORD 结构体之后，开始调用 NTDLL 中的 RtlRaiseException; 之后，开始调用`内核`中 NtRaiseException, NtRaiseException 再调用另外一个内核函数 KiRaiseException。接下来 KiRaiseException 会调用 KiDispatchException 开始异常的分发。

 

https://www.cnblogs.com/Winston/archive/2010/03/16/1687649.html

 

http://runxinzhi.com/Ox9A82-p-5374527.html

 

cpu 异常和模拟异常只有在异常记录不同，调用 KiDispatchException 开始异常的分发后步骤都相同。

 

**异常处理**

3. 内核层用户处理流程
------------

异常可以发生在用户空间，也可以发生在内核空间。无论是 CPU 异常还是模拟异常，是用户层异常还是内核层异常，都要通过`KiDispatchException`函数进行分发。

```
VOID KiDispatchException(ExceptionRecord, ExceptionFrame,TrapFrame,PreviousMode, FirstChance)

```

### [](#（1）kidispatchexception函数分析)（1）KiDispatchException 函数分析

> KiDispatchException 函数执行流程总结
> 
> 1. 将 Trap_Frame 备份到 context 为返回三环做准备  
> 2. 判断先前模式 0 是内核调用 1 是用户层调用  
> 3. 判断是否是第一次调用  
> 4. 判断是否有内核调试器  
> 5. 如果没有内核调试器则不处理  
> 6. 调用 RtlDispatchException 处理异常  
> 7. 如果 RtlDispatchException 返回 FALSE，再次判断是否有内核调试器，没有直接蓝屏

 

(ntoskrnl.dll)

 

1. 将 Trap_frame 备份到 context 为返回 3 环做准备 (由于操作系统不知道分发的异常到底是 3 环的异常还是 0 环的异常，如果是 3 环的异常，进 0 环前的环境会被备份到 Trap_Frame 中，如果要在中途回到 3 环的话，就需要将 **Trap_frame** 备份到 **context**，为返回 3 环做准备)

 

![](https://img-blog.csdnimg.cn/img_convert/76651148f4b37b0623e49e079eaee085.png)

 

![](https://img-blog.csdnimg.cn/img_convert/76f02bc86f1892084056f926a0ba65a8.png)

 

如果没有内核调试器或者内核调试器不处理，都跳转到 **loc_4309A1**

 

调用**_RtlDispatchException** 处理异常

 

![](https://img-blog.csdnimg.cn/img_convert/5a6ca7e295c97087ac82528e58e01085.png)

 

如果 RtlDispatchException 返回 FALSE，再次判断是否有内核调试器，没有直接蓝屏

 

![](https://img-blog.csdnimg.cn/img_convert/3b9b883bf8da6f42765ac219c80d96c5.png)

 

![](https://img-blog.csdnimg.cn/img_convert/d26dd8e63fa45f2821a4b36f10aab1b0.png)

 

![](https://img-blog.csdnimg.cn/img_convert/b323f10bd6f09ccac6b3eb25e9ac5ebe.png)

### [](#（2）rtldispatchexception函数分析)（2）RtlDispatchException 函数分析

RtlDispatchException 函数作用：遍历异常链表，调用异常处理函数，如果异常被正确处理了，该函数返回 1. 如果当前异常处理函数不能处理该异常，那么调用下一个，以此类推。如果到最后也没有人处理这个异常，返回 0。

 

RtlDispatchException 调用_RtlpGetRegistrationHead

 

![](https://img-blog.csdnimg.cn/img_convert/c65652f8d7bb83c26273f5536a3d0e00.png)

 

`RtlpGetRegistrationHead`将`FS:0`保存到 eax 之后返回。我们知道 FS:0 在零环的时候指向的是`KPCR`，而 KPCR 的第一个成员就是`ExceptionList`（具体信息可看以往文章 apc 和系统调用）

 

ExceptionList，指向了一个结构体 `_EXCEPTION_REGISTRATION_RECORD`

 

1.`_EXCEPTION_REGISTRATION_RECORD`结构体必须位于当前线程的堆栈中

```
typedef struct _EXCEPTION_REGISTRATION_RECORD
{
    struct _EXCEPTION_REGISTRATION_RECORD *Next;
    PEXCEPTION_ROUTINE Handler;
} EXCEPTION_REGISTRATION_RECORD;

```

2. 这个结构体有两个成员，第一个成员指向下一个`_EXCEPTION_REGISTRATION_RECORD`，如果没有下一个`_EXCEPTION_REGISTRATION_RECORD`结构体，那么这个地方的值是 - 1。第二个成员是异常处理函数。

 

3. 当调用 **RtlDispatchException** 时，按顺序执行异常处理函数，若其中一个异常处理函数返回结果为真，就不再继续向下执行

 

4. 若执行完所有异常处理函数后，异常仍然没有被处理，那么就返回 FALSE

 

![](https://img-blog.csdnimg.cn/20200216181712198.png?)

4. 用户层异常处理流程
------------

> 1. 上述内核层异常处理中，异常处理函数也在 0 环，不用切换堆栈，用户层异常发生在三环，异常处理函数也在 3 环，所以要切换堆栈（因为 KiDispatchException 在内核，从 0 环返到三环）回到 3 环执行异常处理函数
> 
> 2. 切换堆栈的处理方式与用户 APC 的执行过程几乎是一样的，惟一的区别就是执行用户 APC 时返回 3 环后执行的函数是 KiUserApcDispatcher，而异常处理时返回 3 环后执行的函数是 KiUserExceptionDispatcher
> 
> 3. 理解用户 APC 的执行过程是理解 3 环异常处理的关键

### 分析用户层异常发生时的 KiDispatchException

Trap_Frame 备份到 context

 

![](https://img-blog.csdnimg.cn/img_convert/76651148f4b37b0623e49e079eaee085.png)

 

判断`previousmode`内核调用 还是 用户层调用，如果是用户层调用，jnz 到 loc_42COC2

 

![](https://img-blog.csdnimg.cn/img_convert/76f02bc86f1892084056f926a0ba65a8.png)

 

当不存在内核调试器或者内核调试器没有处理时，跳转到 42C10A

 

![](https://img-blog.csdnimg.cn/img_convert/015aa641c6e59889ede1c85aa1c46bab.png)

 

调用 DbgkForwardException 函数将异常发送给 3 环调试器

 

![](https://img-blog.csdnimg.cn/img_convert/630943c77be4321bb9ad5817bf9df485.png)

 

3 环调试器如果不存在或者没有处理的话，就会开始修改寄存器，准备返回 3 环

 

![](https://img-blog.csdnimg.cn/img_convert/4ef55d4e66da7eb1cac0f0fef6e96baf.png)

 

这里 eax 的值是一个全局变量 KeUserExceptionDispatcher；在操作系统初始化的时候，会给这个全局变量赋一个值，这个值就是 ntdll.KiUserExceptionDispatcher 函数

 

总结：

> 1._KeContextFromKframes 将 Trap_frame 被分到 context 为返回 3 环做准备  
> 2. 判断席安全模式，0 是内核调用，1 是用户层调用  
> 3. 是否都是第一次机会  
> 4. 是否有内核调试器  
> 5. 发送给 3 环调试  
> 6. 如果 3 环调试器没有处理这个异常，修正 EIP 为 KiUserExceptionDispatcher  
> 7.KiUserExceptionDispatcher 函数执行结束：CPU 异常与模拟异常返回地点不同
> 
> 8. 无论通过那种方式，但线程再次回到 3 环时，将执行 KiUserExceptionDispatcher 函数

5.VEH（向量化异常处理）
--------------

当用户异常产生后，内核函数 KiDispatchException 并不是像处理内核异常那样在 0 环直接处理，而是修正 3 环 EIP 为 KiUserExceptionDispatcher 函数后就结束了

 

这样，当线程再次回到 3 环时，将会从 KiUserExceptionDispatcher 函数开始执行

### KiUserExceptionDispatcher 函数分析

![](https://img-blog.csdnimg.cn/img_convert/a6fcd72f3ee8ed1477f3865edecfeb2f.png)

 

调用_RtlDispatchException 找到当前异常的处理函数，处理成功，再次调用 ZwContinue 重新进入 0 环（回到 3 环时，修改了 eip，将返回地址更改为当前函数，因此进入 0 环需要再次修正 eip，ZwContinue 再次进入零环目的就是把修正后的 context 写进 trap_frame 里，再次返回 3 环后，就会从修正后的位置再次执行）

 

![](https://img-blog.csdnimg.cn/img_convert/4726b1749a73601cb91f2225e84bf2ed.png)

 

没有找到当前的处理函数，跳转，调用_ZwRaiseException 对异常进行第二次分发

 

3 环调用了 **RtlCallVectoredExceptionHandlers**，0 环没有调用此函数。

 

![](https://img-blog.csdnimg.cn/img_convert/dbae59e8ec235ed351714c6275c42dba.png)

### _RtlDispatchException 函数分析

> **作用**：
> 
> 1.  查找 **VEH** 链表 (**全局链表**)，如果有则调用，如果没有继续查找局部链表
> 2.  查找 **SEH** 链表 (**局部链表**，在堆栈中)，如果有则调用

 

注意：与内核调用时的区别！

 

VEH：全局链表，无论哪一个线程出现问题，都会先找这个全局链表，VEH 中没有异常处理函数，在查找 SEH 链表，

### **代码：自定义 VEH**

```
typedef PVOID(NTAPI *FnAddVectoredExceptionHandler)(ULONG, _EXCEPTION_POINTERS*);
FnAddVectoredExceptionHandler MyAddVectoredExceptionHandler;
// VEH异常处理只能返回2个值
// EXCEPTION_CONTINUE_EXECUTION 已处理
// EXCEPTION_CONTINUE_SEARCH    未处理
 
//定义VEH的异常处理函数VectExcepHandler，这个函数只能有两个返回值
LONG NTAPI VectExcepHandler(PEXCEPTION_POINTERS pExcepInfo)
{
    MessageBox(NULL,L"VEH异常处理函数执行了...",L"VEH异常",MB_OK);
 
    if (pExcepInfo->ExceptionRecord->ExceptionCode == 0xC0000094)//异常被触发，判断是否是除0异常
    {
 
 
        //1.修改发生异常的代码的Eip    idiv ecx长度2字节 从下一行开始执行
        pExcepInfo->ContextRecord->Eip = pExcepInfo->ContextRecord->Eip + 2;
        //2.将除数修改为1
        //pExcepInfo->ContextRecord->Ecx = 1;
        return EXCEPTION_CONTINUE_EXECUTION;//已处理
    }
 
    return EXCEPTION_CONTINUE_SEARCH;//未处理
}
 
int main()
{
    //动态获取AddVectoredExceptionHandler函数地址
    //AddVectoredExceptionHandler：将异常处理函数插入到VEH全局链表中
    HMODULE hModule = GetModuleHandle(L"Kernel32.dll");
    MyAddVectoredExceptionHandler = (FnAddVectoredExceptionHandler)::GetProcAddress(hModule,"AddVectoredExceptionHandler");
 
    //参数1表示插入VEH链的头部, 0插入到VEH链的尾部
    MyAddVectoredExceptionHandler(0, (_EXCEPTION_POINTERS *)&VectExcepHandler);
 
    //构造除0异常
    int val = 0;
    _asm
    {
        xor edx, edx
        xor ecx, ecx
        mov eax, 100
        idiv ecx        //edx = eax / ecx
                        //异常触发，执行写入的异常处理函数
 
        mov val, edx
    }
 
    printf("val = %d\n",val);
 
    getchar();
}

```

这个异常处理函数的参数是一个结构体指针，有两个成员

```
typedef struct _EXCEPTION_POINTERS
{
    PEXCEPTION_RECORD ExceptionRecord;//异常发生时的信息
    PCONTEXT ContextRecord;//异常发生时的上下文环境
} EXCEPTION_POINTERS, *PEXCEPTION_POINTERS;

```

有了这个参数我们就可以捕获异常发生时的相关信息并且修改异常发生时的寄存器环境。

 

代码中是先判断异常代码是否为除 0 异常，然后修改发生异常的 Eip 和 Ecx，接着返回异常已处理。如果不是除 0 异常就返回异常未处理。

### VEH 异常的处理流程

>

> CPU 捕获异常  
> 通过 KiDispatchException 进行分发 (3 环异常将 EIP 修改为 KiUserExceptionDispatcher)  
> KiUserExceptionDispatcher 调用 RtlDispatchException  
> RtlDispatchException 查找 VEH 处理函数链表，并调用相关处理函数  
> 代码返回到 ZwContinue 再次进入 0 环  
> 线程再次返回 3 环后，从修正的位置开始执行

6.SEH（结构化异常处理）
--------------

​ 当用户异常产生后，内核函数 KiDispatchException 并不是像处理内核异常那样在 0 环直接进行处理，而是修正 3 环 EIP 为 KiUserExceptionDispatcher 函数后就结束了。

 

​ 这样，当线程再次回到 3 环时，将会从 KiUserExceptionDispatcher 函数开始执行。

 

​ KiUserExceptionDispatcher 会调用 RtlDispatchException 函数来查找并调用异常处理函数，查找顺序：

> 1. 先查全局链表：VEH
> 
> 2. 再查局部链表：SEH

 

SEH 是线程相关的，存储在当前线程的堆栈中。

 

三环，FS:0 指向的是 TEB，TEB 的第一个成员是一个子结构体`_NT_TIB`，这个子结构体的第一个成员就是 ExceptionList，异常处理链表

```
typedef struct _EXCEPTION_REGISTRATION_RECORD
{
    struct _EXCEPTION_REGISTRATION_RECORD* Next;    //下一个节点，-1就是没有下一个节点了
    PEXCEPTION_ROUTINE Handler;                     //指向下一个SEH异常处理函数
} EXCEPTION_REGISTRATION_RECORD;

```

![](https://img-blog.csdnimg.cn/20200216182243685.png?)

 

**VEH 异常处理**，全局的链表，想要插入异常处理函数，调用 AddVectoredExceptionHandler 函数；

 

**SEH 异常处理**，想要插入异常处理函数的线程，需要自行插入_EXCEPTION_REGISTRATION_RECORD 这中结构，

### RtlDispatchException 函数分析

![](https://img-blog.csdnimg.cn/img_convert/f991c6a7349875bfbdb3f0e08ebd3151.png)

 

![](https://img-blog.csdnimg.cn/img_convert/8e4866f2d7b1134e0683b1dd346325a5.png)

 

![](https://img-blog.csdnimg.cn/img_convert/6eab380788f468b91803e65374300590.png)

 

[外链图片转存失败, 源站可能有防盗链机制, 建议将图片保存下来直接上传 (img-0u36nuHD-1635589257341)(C:\Users\lenovo\AppData\Roaming\Typora\typora-user-images\image-20211015204834331.png)]

 

![](https://img-blog.csdnimg.cn/img_convert/d0f470322f1ab3968ad50e7a20322f5f.png)

 

![](https://img-blog.csdnimg.cn/img_convert/a3d62c203293c538bc9c94eef0b0adab.png)

 

![](https://img-blog.csdnimg.cn/img_convert/515870c885c13d628f87c20900843a5c.png)

 

![](https://img-blog.csdnimg.cn/img_convert/d94e3db103d4b99e95bf5c77ff00460d.png)

 

handler 必须遵循调用约定，有自己的格式。

```
/*SEH处理函数是提供给RtlDispatchException调用的，所以需要遵循一定的格式。
EXCEPTION_DISPOSITION _cdecl MyEexception_handler
(
    struct _EXCEPTION_RECORD *ExceptionRecord,    //异常结构体
    PVOID EstablisherFrame,                        //SEH结构体地址
    struct _CONTEXT *ContextRecord,                //存储异常发生时的各种寄存器的值 栈位置等
    PVOID DispatcherContext
)
*/

```

**自定义 SEH**

```
#include #include /*
//0环异常处理时讲过这个结构体
typedef struct _EXCEPTION_REGISTRATION_RECORD
{
    struct _EXCEPTION_REGISTRATION_RECORD *Next;
    PEXCEPtiON_ROUTINE Handler;
}
*/
 
 
struct MyException
{
    struct MyException *prev;
    DWORD handler;
};
/*SEH处理函数是提供给RtlDispatchException调用的，所以需要遵循一定的格式。
EXCEPTION_DISPOSITION _cdecl MyEexception_handler
(
    struct _EXCEPTION_RECORD *ExceptionRecord,    //异常结构体
    PVOID EstablisherFrame,                        //SEH结构体地址
    struct _CONTEXT *ContextRecord,                //存储异常发生时的各种寄存器的值 栈位置等
    PVOID DispatcherContext
)
*/
EXCEPTION_DISPOSITION __cdecl MyExceptionHandler(
    struct _EXCEPTION_RECORD *ExceptionRecord,    //ExceptionRecord存储异常信息：什么类型、异常产生位置
    void * EstablisherFrame,                    //MyException结构体地址
    struct _CONTEXT *ContextRecord,                //Context结构体，存储异常发生时各种寄存器的值，堆栈位置等
    void * Dispatchercontext)
{
 
MessageBox(NULL,L"SEH异常处理函数执行了...",L"SEH异常",NULL);
    if (ExceptionRecord->ExceptionCode == 0xC0000094)
    {
        ContextRecord->Eip = ContextRecord->Eip + 2;
 
        ContextRecord->Ecx = 100;
 
        return ExceptionContinueExecution;
    }
 
    return ExceptionContinueSearch;
}
 
 
 
void TestException()
{
    DWORD temp;
 
    //插入异常，必须在当前线程的堆栈当中
    //若定义成全局变量则无效
    MyException myException;
    __asm
    {
        mov eax, FS:[0]
        mov temp, eax
        lea ecx, myException
        mov FS:[0], ecx
    }
 
    //链表插入操作，将原来的也挂入到插入的SEH后面
    myException.prev = (MyException*)temp;
    myException.handler = (DWORD)&MyExceptionHandler;
 
    //构造除0异常
    __asm
    {
        xor edx, edx
        xor ecx, ecx
        mov eax, 0x10
        idiv ecx        //EDX:EAX 除以 ECX
    }
 
    //处理完成，摘掉异常
    __asm
    {
        mov eax, temp
        mov FS:[0], eax
    }
 
    printf("函数执行完毕\n");
}
 
int main()
{
    TestException();   
    return 0;
} 
```

### SEH 异常的处理流程

> 1.  FS:[0] 指向 SEH 链表的第一个成员
> 2.  SEH 的异常处理函数必须在当前线程的堆栈中
> 3.  只有当 VEH 中的异常处理函数不存在或者不处理才会到 SEH 链表中查找

7. 编译器扩展的 SEH
-------------

![](https://img-blog.csdnimg.cn/img_convert/0bc2143ab8825c3e762aabf11487ebdc.png)

 

SEH 的处理流程实际上就是在当前的堆栈中挂一个链表,

 

使用 SEH 这种方式来处理异常要创建一个结构体，挂到当前 TEB 的 ExceptionList 链表里，编写异常处理函数

 

编译器支持的 SEH

```
_try                                   // 挂入链表
{
 
}
_except(过滤表达式)                   // 异常过滤
{
    异常处理程序                      
}

```

> except 里的过滤表达式用于异常过滤，只能有以下三个值：
> 
> EXCEPTION_EXECUTE_HANDLER(1) 异常已经被识别，控制流将进入到 _except 模块中运行异常处理代码  
> EXCEPTION_CONTINUE_SEARCH(0) 异常不被识别，也即当前的这个 _except 模块不是这个异常错误所对应的正确的异常处理模块。 系统将继续到上 _try except 域中继续查找一个恰当的 _except 模块。  
> EXCEPTION_CONTINUE_EXECUTION(-1) 异常被忽略，控制流将在异常出现的点之后，继续恢复运行。
> 
> 过滤表达式只能有三种写法：
> 
> 1.  直接写常量值
> 2.  表达式
> 3.  调用函数

 

手动挂入链表

```
_asm
{                                                 
    mov eax,FS:[0]                       
    mov temp,eax                       
    lea ecx,myException   
    mov FS:[0],ecx                   
}

```

[第五届安全开发者峰会（SDC 2021）10 月 23 日上海召开！限时 2.5 折门票 (含自助午餐 1 份）](https://www.bagevent.com/event/6334937)

最后于 3 小时前 被 pyikaaaa 编辑 ，原因：

[#调试逆向](forum-4-1-1.htm) [#系统底层](forum-4-1-2.htm)